<?php

namespace Backdrop\Sniffs\Functions;

use PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\ForbiddenFunctionsSniff;

/**
 * Catch the use of functions, that have been deprecated in Backdrop core.
 */
class CoreDeprecatedFunctionsSniff extends ForbiddenFunctionsSniff {
  /**
   * List of deprecated functions, pattern: Old function => new function;
   * New function can be NULL, if there's no 1:1 replacement.
   */
  public $forbiddenFunctions = array(
    'backdrop_json_decode_unicode' => NULL,
    'backdrop_json_format' => NULL,
    'backdrop_page_set_cache' => NULL,
    'drupal_access_denied' => 'backdrop_access_denied',
    'drupal_add_css' => 'backdrop_add_css',
    'drupal_add_feed' => 'backdrop_add_feed',
    'drupal_add_html_head' => 'backdrop_add_html_head',
    'drupal_add_html_head_link' => 'backdrop_add_html_head_link',
    'drupal_add_http_header' => 'backdrop_add_http_header',
    'drupal_add_js' => 'backdrop_add_js',
    'drupal_add_library' => 'backdrop_add_library',
    'drupal_add_tabledrag' => 'backdrop_add_tabledrag',
    'drupal_aggregate_css' => 'backdrop_aggregate_css',
    'drupal_aggregate_js' => 'backdrop_aggregate_js',
    'drupal_alter' => 'backdrop_alter',
    'drupal_anonymous_user' => 'backdrop_anonymous_user',
    'drupal_array_get_nested_value' => 'backdrop_array_get_nested_value',
    'drupal_array_merge_deep' => NULL,
    'drupal_array_merge_deep_array' => 'backdrop_array_merge_deep_array',
    'drupal_array_nested_key_exists' => 'backdrop_array_nested_key_exists',
    'drupal_array_set_nested_value' => 'backdrop_array_set_nested_value',
    'drupal_array_unset_nested_value' => 'backdrop_array_unset_nested_value',
    'drupal_attributes' => 'backdrop_attributes',
    'drupal_autoload_class' => 'backdrop_autoload',
    'drupal_autoload_interface' => 'backdrop_autoload',
    'drupal_base64_encode' => 'backdrop_base64_encode',
    'drupal_basename' => 'backdrop_basename',
    'drupal_bootstrap' => 'backdrop_bootstrap',
    'drupal_build_css_cache' => 'backdrop_build_css_cache',
    'drupal_build_form' => 'backdrop_build_form',
    'drupal_build_js_cache' => 'backdrop_build_js_cache',
    'drupal_cache_system_paths' => 'backdrop_cache_system_paths',
    'drupal_check_incompatibility' => 'backdrop_check_incompatibility',
    'drupal_check_module' => 'backdrop_check_module',
    'drupal_check_profile' => 'backdrop_check_profile',
    'drupal_chmod' => 'backdrop_chmod',
    'drupal_clean_css_identifier' => 'backdrop_clean_css_identifier',
    'drupal_clear_path_cache' => 'backdrop_clear_path_cache',
    'drupal_clear_css_cache' => 'backdrop_clear_css_cache',
    'drupal_clear_js_cache' => 'backdrop_clear_js_cache',
    'drupal_common_theme' => 'backdrop_common_theme',
    'drupal_convert_to_utf8' => 'backdrop_convert_to_utf8',
    'drupal_cron_run' => 'backdrop_cron_run',
    'drupal_current_script_url' => 'backdrop_current_script_url',
    'drupal_delete_file_if_stale' => 'backdrop_delete_file_if_stale',
    'drupal_deliver_html_page' => 'backdrop_deliver_html_page',
    'drupal_deliver_page' => 'backdrop_deliver_page',
    'drupal_depth_first_search' => 'backdrop_depth_first_search',
    'drupal_detect_baseurl' => 'backdrop_detect_baseurl',
    'drupal_detect_database_types' => NULL,
    'drupal_dirname' => 'backdrop_dirname',
    'drupal_encode_path' => 'backdrop_encode_path',
    'drupal_environment_initialize' => 'backdrop_environment_initialize',
    'drupal_error_levels' => 'backdrop_error_levels',
    'drupal_exit' => 'backdrop_exit',
    'drupal_explode_tags' => 'backdrop_explode_tags',
    'drupal_fast_404' => 'fast_404',
    'drupal_find_base_themes' => 'backdrop_find_base_themes',
    'drupal_find_theme_functions' => 'backdrop_find_theme_functions',
    'drupal_find_theme_templates' => 'backdrop_find_theme_templates',
    'drupal_flush_all_caches' => 'backdrop_flush_all_caches',
    'drupal_form_submit' => 'backdrop_form_submit',
    'drupal_generate_test_ua' => 'backdrop_generate_test_ua',
    'drupal_get_bootstrap_phase' => 'backdrop_get_bootstrap_phase',
    'drupal_get_breadcrumb' => 'backdrop_get_breadcrumb',
    'drupal_get_complete_schema' => 'backdrop_get_complete_schema',
    'drupal_get_css' => 'backdrop_get_css',
    'drupal_get_database_types' => NULL,
    'drupal_get_destination' => 'backdrop_get_destination',
    'drupal_get_feeds' => 'backdrop_get_feeds',
    'drupal_get_filename' => 'backdrop_get_filename',
    'drupal_get_filetransfer_info' => 'backdrop_get_filetransfer_info',
    'drupal_get_form' => 'backdrop_get_form',
    'drupal_get_hash_salt' => 'backdrop_get_hash_salt',
    'drupal_get_html_head' => 'backdrop_get_html_head',
    'drupal_get_http_header' => 'backdrop_get_http_header',
    'drupal_get_installed_schema_version' => 'backdrop_get_installed_schema_version',
    'drupal_get_js' => 'backdrop_get_js',
    'drupal_get_library' => 'backdrop_get_library',
    'drupal_get_messages' => 'backdrop_get_messages',
    'drupal_get_normal_path' => 'backdrop_get_normal_path',
    'drupal_get_path' => 'backdrop_get_path',
    'drupal_get_path_alias' => 'backdrop_get_path_alias',
    'drupal_get_private_key' => 'backdrop_get_private_key',
    'drupal_get_profile' => 'backdrop_get_profile',
    'drupal_get_query_array' => 'backdrop_get_query_array',
    'drupal_get_query_parameters' => 'backdrop_get_query_parameters',
    'drupal_get_schema' => 'backdrop_get_schema',
    'drupal_get_schema_unprocessed' => 'backdrop_get_schema_unprocessed',
    'drupal_get_schema_versions' => 'backdrop_get_schema_versions',
    'drupal_get_title' => 'backdrop_get_title',
    'drupal_get_token' => 'backdrop_get_token',
    'drupal_get_updaters' => 'backdrop_get_updaters',
    'drupal_get_user_timezone' => 'backdrop_get_user_timezone',
    'drupal_goto' => 'backdrop_goto',
    'drupal_group_css' => 'backdrop_group_css',
    'drupal_group_js' => 'backdrop_group_js',
    'drupal_hash_base64' => 'backdrop_hash_base64',
    'drupal_hmac_base64' => 'backdrop_hmac_base64',
    'drupal_html_class' => 'backdrop_html_class',
    'drupal_html_id' => 'backdrop_html_id',
    'drupal_html_to_text' => 'backdrop_html_to_text',
    'drupal_http_build_query' => 'backdrop_http_build_query',
    'drupal_http_header_attributes' => 'backdrop_http_header_attributes',
    'drupal_http_request' => 'backdrop_http_request',
    'drupal_implode_tags' => 'backdrop_implode_tags',
    'drupal_installation_attempted' => 'backdrop_installation_attempted',
    'drupal_install_mkdir' => 'backdrop_install_mkdir',
    'drupal_install_profile_distribution_name' => 'backdrop_install_profile_distribution_name',
    'drupal_install_schema' => 'backdrop_install_schema',
    'drupal_install_system' => 'backdrop_install_system',
    'drupal_is_cli' => 'backdrop_is_cli',
    'drupal_is_front_page' => 'backdrop_is_front_page',
    'drupal_json_decode' => 'backdrop_json_decode',
    'drupal_json_encode' => 'backdrop_json_encode',
    'drupal_json_output' => 'backdrop_json_output',
    'drupal_js_defaults' => 'backdrop_js_defaults',
    'drupal_language_initialize' => 'backdrop_language_initialize',
    'drupal_load' => 'backdrop_load',
    'drupal_load_stylesheet' => 'backdrop_load_stylesheet',
    'drupal_load_stylesheet_content' => 'backdrop_load_stylesheet_content',
    'drupal_load_updates' => 'backdrop_load_updates',
    'drupal_lookup_path' => 'backdrop_lookup_path',
    'drupal_mail' => 'backdrop_mail',
    'drupal_mail_system' => 'backdrop_mail_system',
    'drupal_maintenance_theme' => 'backdrop_maintenance_theme',
    'drupal_map_assoc' => 'backdrop_map_assoc',
    'drupal_match_path' => 'backdrop_match_path',
    'drupal_mkdir' => 'backdrop_mkdir',
    'drupal_move_uploaded_file' => 'backdrop_move_uploaded_file',
    'drupal_not_found' => 'backdrop_not_found',
    'drupal_override_server_variables' => 'backdrop_override_server_variables',
    'drupal_page_footer' => 'backdrop_page_footer',
    'drupal_page_get_cache' => 'backdrop_page_get_cache',
    'drupal_page_header' => 'backdrop_page_header',
    'drupal_page_is_cacheable' => 'backdrop_page_is_cacheable',
    'drupal_page_set_cache' => 'backdrop_page_set_cache',
    'drupal_parse_dependency' => 'backdrop_parse_dependency',
    'drupal_parse_info_file' => 'backdrop_parse_info_file',
    'drupal_parse_info_format' => 'backdrop_parse_info_format',
    'drupal_parse_url' => 'backdrop_parse_url',
    'drupal_path_alias_allowlist_rebuild' => NULL,
    'drupal_path_alias_whitelist_rebuild' => NULL,
    'drupal_path_initialize' => 'backdrop_path_initialize',
    'drupal_placeholder' => 'backdrop_placeholder',
    'drupal_prepare_form' => 'backdrop_prepare_form',
    'drupal_pre_render_conditional_comments' => NULL,
    'drupal_pre_render_link' => 'backdrop_pre_render_link',
    'drupal_pre_render_links' => 'backdrop_pre_render_links',
    'drupal_pre_render_markup' => 'backdrop_pre_render_markup',
    'drupal_pre_render_scripts' => 'backdrop_pre_render_scripts',
    'drupal_pre_render_styles' => 'backdrop_pre_render_styles',
    'drupal_process_attached' => 'backdrop_process_attached',
    'drupal_process_form' => 'backdrop_process_form',
    'drupal_process_states' => 'backdrop_process_states',
    'drupal_random_bytes' => 'backdrop_random_bytes',
    'drupal_random_key' => 'backdrop_random_key',
    'drupal_realpath' => 'backdrop_realpath',
    'drupal_rebuild_form' => 'backdrop_rebuild_form',
    'drupal_redirect_form' => 'backdrop_redirect_form',
    'drupal_region_class' => 'backdrop_region_class',
    'drupal_register_shutdown_function' => 'backdrop_register_shutdown_function',
    'drupal_render' => 'backdrop_render',
    'drupal_render_cache_by_query' => 'backdrop_render_cache_by_query',
    'drupal_render_cache_get' => 'backdrop_render_cache_get',
    'drupal_render_cache_set' => 'backdrop_render_cache_set',
    'drupal_render_children' => 'backdrop_render_children',
    'drupal_render_cid_create' => 'backdrop_render_cid_create',
    'drupal_render_cid_parts' => 'backdrop_render_cid_parts',
    'drupal_render_collect_attached' => 'backdrop_render_collect_attached',
    'drupal_render_page' => 'backdrop_render_page',
    'drupal_required_modules' => 'backdrop_required_modules',
    'drupal_requirements_severity' => 'backdrop_requirements_severity',
    'drupal_requirements_url' => 'backdrop_requirements_url',
    'drupal_retrieve_form' => 'backdrop_retrieve_form',
    'drupal_rewrite_settings' => 'backdrop_rewrite_settings',
    'drupal_rmdir' => 'backdrop_rmdir',
    'drupal_save_session' => 'backdrop_save_session',
    'drupal_schema_fields_sql' => 'backdrop_schema_fields_sql',
    'drupal_send_headers' => 'backdrop_send_headers',
    'drupal_serve_page_from_cache' => 'backdrop_serve_page_from_cache',
    'drupal_session_commit' => 'backdrop_session_commit',
    'drupal_session_destroy_uid' => 'backdrop_session_destroy_uid',
    'drupal_session_initialize' => 'backdrop_session_initialize',
    'drupal_session_regenerate' => 'backdrop_session_regenerate',
    'drupal_session_start' => 'backdrop_session_start',
    'drupal_session_started' => 'backdrop_session_started',
    'drupal_settings_initialize' => 'backdrop_settings_initialize',
    'drupal_set_breadcrumb' => 'backdrop_set_breadcrumb',
    'drupal_set_installed_schema_version' => 'backdrop_set_installed_schema_version',
    'drupal_set_message' => 'backdrop_set_message',
    'drupal_set_time_limit' => 'backdrop_set_time_limit',
    'drupal_set_title' => 'backdrop_set_title',
    'drupal_site_offline' => 'backdrop_site_offline',
    'drupal_sort_title' => 'backdrop_sort',
    'drupal_sort_weight' => 'backdrop_sort',
    'drupal_static' => 'backdrop_static',
    'drupal_static_reset' => 'backdrop_static_reset',
    'drupal_strip_dangerous_protocols' => 'backdrop_strip_dangerous_protocols',
    'drupal_strlen' => 'backdrop_strlen',
    'drupal_strtolower' => 'backdrop_strtolower',
    'drupal_strtoupper' => 'backdrop_strtoupper',
    'drupal_substr' => 'backdrop_substr',
    'drupal_system_listing' => 'backdrop_system_listing',
    'drupal_tempnam' => 'backdrop_tempnam',
    'drupal_theme_access' => 'backdrop_theme_access',
    'drupal_theme_initialize' => 'backdrop_theme_initialize',
    'drupal_theme_rebuild' => 'backdrop_theme_rebuild',
    'drupal_truncate_bytes' => 'backdrop_truncate_bytes',
    'drupal_ucfirst' => 'backdrop_ucfirst',
    'drupal_uninstall_modules' => 'backdrop_uninstall_modules',
    'drupal_uninstall_schema' => 'backdrop_uninstall_schema',
    'drupal_unlink' => 'backdrop_unlink',
    'drupal_unpack' => 'backdrop_unpack',
    'drupal_validate_form' => 'backdrop_validate_form',
    'drupal_validate_utf8' => 'backdrop_validate_utf8',
    'drupal_valid_http_host' => 'backdrop_valid_http_host',
    'drupal_valid_path' => 'backdrop_valid_path',
    'drupal_valid_test_ua' => 'backdrop_valid_test_ua',
    'drupal_valid_token' => 'backdrop_valid_token',
    'drupal_var_export' => 'backdrop_var_export',
    'drupal_verify_install_file' => 'backdrop_verify_install_file',
    'drupal_verify_profile' => 'backdrop_verify_profile',
    'drupal_wrap_mail' => 'backdrop_wrap_mail',
    'drupal_write_record' => 'backdrop_write_record',
    'drupal_xml_parser_create' => 'backdrop_xml_parser_create',
    'element_sort' => 'backdrop_sort',
    'element_sort_by_title' => 'backdrop_sort',
    'element_validate_integer' => NULL,
    'element_validate_integer_positive' => NULL,
    'element_validate_number' => NULL,
    'entity_create_stub_entity' => NULL,
    'file_create_htaccess' => 'file_save_htaccess',
    'file_displays' => 'file_display',
    'file_displays_load' => 'file_display_load',
    'file_entity_access' => 'file_access',
    'file_fnmatch' => NULL,
    'filter_list_format' => NULL,
    'format_username' => 'user_format_name',
    'image_style_path_token' => NULL,
    'install_drupal' => 'install_backdrop',
    'node_types_rebuild' => 'node_type_cache_reset',
    'system_check_http_request' => NULL,
    'system_get_date_types' => NULL,
    'taxonomy_get_children' => 'taxonomy_term_load_children',
    'taxonomy_get_parents' => 'taxonomy_term_load_parents',
    'taxonomy_get_parents_all' => 'taxonomy_term_load_parents_all',
    'taxonomy_get_term_by_name' => 'taxonomy_term_load_multiple_by_name',
    'taxonomy_vocabulary_get_names' => 'taxonomy_vocabulary_load_multiple',
    'taxonomy_vocabulary_machine_name_load' => 'taxonomy_vocabulary_load',
    'theme_file_type_overview' => NULL,
    'theme_menu_admin_overview' => NULL,
    'theme_node_admin_overview' => NULL,
    'theme_views_ui_view_name' => NULL,
    'user_role_load_by_name' => 'user_role_load',
    'variable_del' => NULL,
    'variable_get' => NULL,
    'variable_initialize' => NULL,
    'variable_set' => NULL,
    'views_clean_css_identifier' => 'backdrop_clean_css_identifier',
    'views_ui_build_form_url' => 'views_ui_build_form_path',
  );

  /**
   * Make this a warning, so it doesn't cause false positives in core checks.
   */
  public $error = FALSE;

  /**
   * Custom error wording.
   */
  protected function addError($phpcsFile, $stackPtr, $function, $pattern = NULL) {
    $data = [$function];
    $error = 'Function %s() has been deprecated';
    if ($replacement = $this->forbiddenFunctions[$function]) {
      $data[] = $replacement;
      $error .= '; use %s() instead.';
    }
    $type = 'CoreDeprecated';

    if ($this->error === TRUE) {
      $phpcsFile->addError($error, $stackPtr, $type, $data);
    }
    else {
      $phpcsFile->addWarning($error, $stackPtr, $type, $data);
    }
  }
}
